apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/api
images:
- name: API_IMAGE
  newName: andersondarioo/api
  newTag: e63e5577daff77a47b34a51cf73ba14532357a22