apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: argocd
  source:
    helm:
      version: v3
      valueFiles:
      - values.yaml
    path: argocd-install/argo-cd
    repoURL: https://github.com/andersondario/kubernetes-gitops.git
    targetRevision: HEAD
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-appprojects
  namespace: argocd
spec:
  project: argocd
  source:
    path: argocd-appprojects
    repoURL: https://github.com/andersondario/kubernetes-gitops.git
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-applications
  namespace: argocd
spec:
  project: argocd
  source:
    path: argocd-applications
    repoURL: https://github.com/andersondario/kubernetes-gitops.git
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true