# apiVersion: argoproj.io/v1alpha1
# kind: AppProject
# metadata:
#   name: Apps-Team-A
#   namespace: argocd
# spec:
#   description: Microservices-sample Project
#   sourceRepos:
#   - 'https://github.com/andersondario/kubernetes-gitops.git'
#   destinations:
#   - namespace: dev
#     server: https://kubernetes.default.svc
#   - namespace: prod
#     server: https://kubernetes.default.svc  
#   clusterResourceWhitelist:
#   - group: '*'
#     kind: '*'
#   orphanedResources:
#     warn: true