apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    helm:
      version: v3
    path: manifests/infra/monitoring/grafana
    repoURL: 'https://github.com/andersondario/kubernetes-gitops.git'
    targetRevision: HEAD
  project: infrastructure
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true