apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
spec:
  destination:
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  source:
    helm:
      version: v3
    path: manifests/infra/network/istio-base
    repoURL: 'https://github.com/andersondario/kubernetes-gitops.git'
    targetRevision: HEAD
  project: infrastructure
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
spec:
  destination:
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  source:
    helm:
      version: v3
    path: manifests/infra/network/istiod
    repoURL: 'https://github.com/andersondario/kubernetes-gitops.git'
    targetRevision: HEAD
  project: infrastructure
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true